// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: siddhi_MI_connect.proto

package org.wso2.extension.siddhi.map.protobuf.utils.service;

public interface EmptyResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:invokesequence.EmptyResponse)
    com.google.protobuf.MessageOrBuilder {
}
