// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: siddhi_MI_connect.proto

package org.wso2.extension.siddhi.map.protobuf.utils.service;

public interface SequenceCallRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:invokesequence.SequenceCallRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string sequenceName = 1;</code>
   */
  String getSequenceName();
  /**
   * <code>string sequenceName = 1;</code>
   */
  com.google.protobuf.ByteString
      getSequenceNameBytes();

  /**
   * <pre>
   *json or xml
   * </pre>
   *
   * <code>string payloadAsJSON = 2;</code>
   */
  String getPayloadAsJSON();
  /**
   * <pre>
   *json or xml
   * </pre>
   *
   * <code>string payloadAsJSON = 2;</code>
   */
  com.google.protobuf.ByteString
      getPayloadAsJSONBytes();

  /**
   * <code>map&lt;string, string&gt; synapseConfigs = 3;</code>
   */
  int getSynapseConfigsCount();
  /**
   * <code>map&lt;string, string&gt; synapseConfigs = 3;</code>
   */
  boolean containsSynapseConfigs(
          String key);
  /**
   * Use {@link #getSynapseConfigsMap()} instead.
   */
  @Deprecated
  java.util.Map<String, String>
  getSynapseConfigs();
  /**
   * <code>map&lt;string, string&gt; synapseConfigs = 3;</code>
   */
  java.util.Map<String, String>
  getSynapseConfigsMap();
  /**
   * <code>map&lt;string, string&gt; synapseConfigs = 3;</code>
   */

  String getSynapseConfigsOrDefault(
          String key,
          String defaultValue);
  /**
   * <code>map&lt;string, string&gt; synapseConfigs = 3;</code>
   */

  String getSynapseConfigsOrThrow(
          String key);
}
